---

changelog:
  exclude:
    labels:
      - changelog:skip
  categories:
    - title: 🚨 Breaking Changes
      labels:
        - changelog:breaking-change

    - title: 🫥 Deprecated Changes
      labels:
        - changelog:deprecated

    - title: 🔒 Security
      labels:
        - changelog:security

    - title: 🚀 Features
      labels:
        - changelog:feature

    - title: 🌟 Enhancements
      labels:
        - changelog:enhancement

    - title: 🐛 Bug fixes
      labels:
        - changelog:bugfix

    - title: 📚 Documentation
      labels:
        - changelog:documentation
